// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestPostgresqlWebApplication;

#nullable disable

namespace TestPostgresqlWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230131053648_AddSmartScaleTable")]
    partial class AddSmartScaleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestPostgresqlWebApplication.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TestPostgresqlWebApplication.PersonInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<float?>("Beauty")
                        .HasColumnType("real");

                    b.Property<int>("Ctime")
                        .HasColumnType("integer");

                    b.Property<string>("FaceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool?>("Glass")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Hat")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FaceNo")
                        .IsUnique();

                    b.ToTable("PersonInfos");
                });

            modelBuilder.Entity("TestPostgresqlWebApplication.SmartScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ctime")
                        .HasColumnType("integer");

                    b.Property<string>("FaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SmartScales");
                });
#pragma warning restore 612, 618
        }
    }
}
